services:
  telegram-bot:
    build: .
    container_name: underbridge-tg
    restart: always
    env_file: 
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000" # Optional, for debugging purposes
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
