services:
  bot:
    image: msazanov/underbridge-tg:latest
    container_name: telegram-vpn-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - vpn_bridge_network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpn_bridge_network

volumes:
  postgres_data:

networks:
  vpn_bridge_network:
    driver: bridge
