name: Docker Build and Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Git configuration for version bump
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Increment the version in package.json
      - name: Increment version
        run: npm version patch --no-git-tag-version

      # Commit the updated package.json
      - name: Commit updated version
        run: |
          git add package.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Extract the version from package.json
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Define tag based on branch
      - name: Define Docker Tag
        id: define_tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DOCKER_TAG=stable" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=unstable" >> $GITHUB_ENV
          fi

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/underbridge-tg:${{ env.VERSION }}-${{ env.DOCKER_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/underbridge-tg:${{ env.DOCKER_TAG }}
