name: Docker Build and Push

on:
  push:
    branches:
      - main # Укажите ветку, для которой запускается workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set version based on the latest Git tag or commit hash
      - name: Set Image Version
        id: vars
        run: |
          # Получаем последнюю версию из git тегов
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          # Увеличиваем версию на патч
          VERSION=$(echo "$TAG" | awk -F. '{printf "v%d.%d.%d", $1, $2, $3+1}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION: $VERSION"

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Build and push Docker image with version and latest tags
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/underbridge-tg:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/underbridge-tg:latest
